ShopGUI:
  Name: Furniture Shop
  LayoutPattern:
    - BBBBBBBBB
    - BFFFFFFFB
    - BFFFFFFFB
    - BFFFFFFFB
    - BFFFFFFFB
    - BBBBBBBBB
  Layout:
    B:
      Type: VANILLA
      Material: BLACK_STAINED_GLASS_PANE
      DisplayName: ''
      Lore: []
      #amount: 1
      #modelData: 0
    F:
      Type: VANILLA
      Material: WHITE_STAINED_GLASS_PANE
      DisplayName: ''
      Lore: []
      #amount: 1
      #modelData: 0

ConfirmGUI:
  Name: Confirm Purchase
  LayoutPattern:
    - BBBBBBBBB
    - B123PAAAB
    - B456DSTBB
  Layout:
    B:
      Type: VANILLA
      Material: BLACK_STAINED_GLASS_PANE
      DisplayName: ''
      Lore: []
      #amount: 1
      #modelData: 0
    D:
      Type: VANILLA
      Material: RED_STAINED_GLASS_PANE
      DisplayName: ''
      Lore: []
      #amount: 1
      #modelData: 0
    A:
      Type: VANILLA
      Material: GREEN_STAINED_GLASS_PANE
      DisplayName: ''
      Lore: []
      #amount: 1
      #modelData: 0
    P:
      Type: VANILLA
      Material: PAPER
      DisplayName: '&aPreview'
      Lore: []
      #amount: 1
      #modelData: 0
    '1':
      Type: VANILLA
      Material: LIME_STAINED_GLASS_PANE
      DisplayName: '&a+1'
      Lore: []
    '2':
      Type: VANILLA
      Material: LIME_STAINED_GLASS_PANE
      DisplayName: '&a+8'
      Lore: []
    '3':
      Type: VANILLA
      Material: LIME_STAINED_GLASS_PANE
      DisplayName: '&a+16'
      Lore: []
    '4':
      Type: VANILLA
      Material: RED_STAINED_GLASS_PANE
      DisplayName: '&c-1'
      Lore: []
    '5':
      Type: VANILLA
      Material: RED_STAINED_GLASS_PANE
      DisplayName: '&c-8'
      Lore: []
    '6':
      Type: VANILLA
      Material: RED_STAINED_GLASS_PANE
      DisplayName: '&c-16'
      Lore: []
    S:
      Type: VANILLA
      Material: YELLOW_STAINED_GLASS_PANE
      DisplayName: '&eSet 1'
      Lore: []
    T:
      Type: VANILLA
      Material: YELLOW_STAINED_GLASS_PANE
      DisplayName: '&eSet 64'
      Lore: []

Shop:
  #Shop Display Location [x, y, z]
  DisplayLocation: [0, 0, 0]
  DisplayWorld: world
  #Display Yaw Rotation (0-360 degrees)
  DisplayYaw: 0.0
  #Auto center display to block center (X and Z only, not Y)
  AutoCenterDisplay: false
  #Cleanup radius for removing old entities
  CleanupRadius: 3.0
  #Worldguard Region
  WorldguardRegion: 'FurnitureShop'
  #Display Interval in Ticks
  DisplayInterval: 100
  #Should the shop stop random display when player are nearby
  PauseDisplayRange: 5
  ShopArea: [10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34,37,38,39,40,41,42,43]
  PrevPage: [45]
  NextPage: [53]

Confirm:
  Deny: [22]
  Accept: [14, 15, 16]
  Preview: [13]
  Add1: [10]
  Add8: [11]
  Add16: [12]
  Remove1: [19]
  Remove8: [20]
  Remove16: [21]
  Set1: [23]
  Set64: [24]
